# Generated by Django 2.2.12 on 2021-05-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210503_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.IntegerField(null=True),
        ),
    ]
