# Generated by Django 2.2.12 on 2021-05-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210503_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='users',
            field=models.IntegerField(null=True),
        ),
    ]
