# Generated by Django 2.2.12 on 2021-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210328_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='categories',
        ),
        migrations.AddField(
            model_name='categories',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.Listings'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
