# Generated by Django 2.2.12 on 2021-04-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='comments',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
