# Generated by Django 2.2.12 on 2021-04-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listings_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='commenter',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
