# Generated by Django 2.2.12 on 2021-04-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210423_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auctions.Comments'),
        ),
    ]
